# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20190307_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(verbose_name='商品数量')),
                ('price', models.FloatField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Order')),
            ],
        ),
    ]
